#define COLOR_CONTACT			0.19,	0.39,	0.56	// Official DLC color, see https://confluence.bistudio.com/display/CONTACT/Color+Palette

#define COLOR_FREQUENCY			1.00,	1.00,	0.00

#define COLOR_ANTENNA			0.14,	0.29,	0.42	// EM antenna color shown in the map
#define COLOR_ANTENNA_EXPIRED		0.29,	0.41,	0.50	// EM antenna which hasn't been tracked for some time

#define COLOR_ANTENNA_ENEMY		1.00,	0.00,	0.00	// EM enemy antenna color shown in the map
#define COLOR_ANTENNA_ENEMY_EXPIRED	0.80,	0.40,	0.40	// EM enemy antenna which hasn't been tracked for some time

#define COLOR_TASK			1.00,	0.50,	0.00	// Color of active task
#define COLOR_TASK_CURRENT		COLOR_TASK//1.00,	0.60,	0.00	// Color of current task (only on task can be current)

#define COLOR_SIGNAL			0.32,	0.99,	0.79	// Signal color
#define COLOR_SIGNAL_SELECTED		0.28,	0.73,	1.00	// Selected band in spectrum analyzer

#define COLOR_ENEMY			0.50,	0.00,	0.00	// Enemy forces

#define COLOR_PROBE			0.52,	0.68,	0.28