///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Macros
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define CHECKBOX_TEXTURE(UNCHECKED,CHECKED)\
	textureChecked = CHECKED;\
	textureUnchecked = UNCHECKED;\
	textureFocusedChecked = CHECKED;\
	textureFocusedUnchecked = UNCHECKED;\
	textureHoverChecked = CHECKED;\
	textureHoverUnchecked = UNCHECKED;\
	texturePressedChecked = CHECKED;\
	texturePressedUnchecked = UNCHECKED;\
	textureDisabledChecked = CHECKED;\
	textureDisabledUnchecked = UNCHECKED;