DEPRECATED_CLASS(B_G_UAV_06_F,Atlas_B_G_UAV_06_F);
DEPRECATED_CLASS(B_G_UAV_06_medical_F,Atlas_B_G_UAV_06_medical_F);
DEPRECATED_CLASS(I_I_UAV_06_backpack_F,Atlas_I_I_UAV_06_backpack_F);
DEPRECATED_CLASS(I_I_UAV_06_F,Atlas_I_I_UAV_06_F);
DEPRECATED_CLASS(I_I_UAV_06_medical_backpack_F,Atlas_I_I_UAV_06_medical_backpack_F);
DEPRECATED_CLASS(I_I_UAV_06_medical_F,Atlas_I_I_UAV_06_medical_F);