class CfgVehicles
{
    /* Definitions */
    #include "\A3_Aegis\macros_itemHolders.hpp"
    
    /* Bases */
	class Vest_Base_F;

    /* Items */
	class Vest_V_Rangemaster_belt: Vest_Base_F
	{
		displayName = $STR_A3_A_CfgWeapons_V_Rangemaster_belt0;
	};
	class Vest_V_TacVestIR_blk: Vest_Base_F
	{
		scope = protected;
		scopeCurator = private;
	};
	class Vest_V_HarnessO_brn: Vest_Base_F
	{
		displayName = $STR_A3_A_CfgWeapons_V_HarnessO_brn0;
	};
	class Vest_V_HarnessOGL_brn: Vest_Base_F
	{
		displayName = $STR_A3_A_CfgWeapons_V_HarnessOGL_brn0;
	};
	VEST_HOLDER(V_HarnessOSpec_brn,$STR_A3_A_CfgWeapons_V_HarnessOSpec_brn0);
	VEST_HOLDER(V_HarnessOSpec_gry,$STR_A3_V_HarnessOSpec_gry0);
	class Vest_V_SmershVest_01_F: Vest_Base_F
	{
		displayName = $STR_A3_A_CfgWeapons_V_SmershVest_01_F0;
	};
	class Vest_V_SmershVest_01_radio_F: Vest_Base_F
	{
		displayName = $STR_A3_A_CfgWeapons_V_SmershVest_01_radio_F0;
	};
    class Vest_V_CarrierRigKBT_01_Olive_F;
    class Vest_V_CarrierRigKBT_01_light_Olive_F;
    class Vest_V_CarrierRigKBT_01_heavy_Olive_F;
	VEST_HOLDER(V_Rangemaster_belt_khk,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_khk0);
	VEST_HOLDER(V_Rangemaster_belt_cbr,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_cbr0);
	VEST_HOLDER(V_Rangemaster_belt_blk,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_blk0);
	VEST_HOLDER(V_Rangemaster_belt_oli,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_oli0);
	VEST_HOLDER(V_PlateCarrier1_cbr,$STR_A3_V_PlateCarrier1_cbr0);
	VEST_HOLDER(V_PlateCarrier2_cbr,$STR_A3_V_PlateCarrier2_cbr0);
	VEST_HOLDER(V_PlateCarrier1_mtp,$STR_A3_A_CfgWeapons_V_PlateCarrier1_mtp0);
	VEST_HOLDER(V_PlateCarrier2_mtp,$STR_A3_A_CfgWeapons_V_PlateCarrier2_mtp0);
	VEST_HOLDER(V_PlateCarrier1_khk,$STR_A3_A_CfgWeapons_V_PlateCarrier1_khk0);
	VEST_HOLDER(V_PlateCarrier2_khk,$STR_A3_A_CfgWeapons_V_PlateCarrier2_khk0);
	VEST_HOLDER(V_PlateCarrier1_oli,$STR_A3_A_CfgWeapons_V_PlateCarrier1_oli0);
	VEST_HOLDER(V_PlateCarrier2_oli,$STR_A3_A_CfgWeapons_V_PlateCarrier2_oli0);
	VEST_HOLDER(V_PlateCarrierGL_cbr,$STR_A3_V_PlateCarrierGL_cbr0);
	VEST_HOLDER(V_PlateCarrierSpec_cbr,$STR_A3_V_PlateCarrierSpec_cbr0);
	VEST_HOLDER(V_ChestrigF_khk,$STR_A3_V_ChestrigB_khk0);
	VEST_HOLDER(V_ChestrigF_rgr,$STR_A3_V_ChestrigB_rgr0);
	VEST_HOLDER(V_ChestrigF_blk,$STR_A3_V_ChestrigB_blk0);
	VEST_HOLDER(V_ChestrigF_oli,$STR_A3_A_CfgWeapons_V_ChestrigF_oli0);
	VEST_HOLDER(V_TacVest_gry,$STR_A3_A_CfgWeapons_V_TacVest_gry0);
	VEST_HOLDER(V_HarnessO_blk,$STR_A3_A_CfgWeapons_V_HarnessO_blk0);
	VEST_HOLDER(V_HarnessOGL_blk,$STR_A3_A_CfgWeapons_V_HarnessOGL_blk0);
	VEST_HOLDER(V_HarnessO_oicamo,$STR_A3_A_CfgWeapons_V_HarnessO_oicamo0);
	VEST_HOLDER(V_HarnessOGL_oicamo,$STR_A3_A_CfgWeapons_V_HarnessOGL_oicamo0);
	VEST_HOLDER(V_HarnessOSpec_blk,$STR_A3_A_CfgWeapons_V_HarnessOSpec_blk0);
	VEST_HOLDER(V_HarnessOSpec_oicamo,$STR_A3_A_CfgWeapons_V_HarnessOSpec_oicamo0);
	VEST_HOLDER(V_PlateCarrierIA1_oli,$STR_A3_A_CfgWeapons_V_PlateCarrierIA1_oli0);
	VEST_HOLDER(V_PlateCarrierIA1_khk,$STR_A3_A_CfgWeapons_V_PlateCarrierIA1_khk0);
	VEST_HOLDER(V_PlateCarrierIA2_oli,$STR_A3_A_CfgWeapons_V_PlateCarrierIA2_oli0);
	VEST_HOLDER(V_PlateCarrierIA2_khk,$STR_A3_A_CfgWeapons_V_PlateCarrierIA2_khk0);
	VEST_HOLDER(V_PlateCarrierIAGL_khk,$STR_A3_A_CfgWeapons_V_PlateCarrierIAGL_khk0);
	VEST_HOLDER(V_Rangemaster_belt_tna_F,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_tna_F0);
	VEST_HOLDER(V_Rangemaster_belt_ghex_F,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_ghex_F0);
	VEST_HOLDER(V_HarnessOSpec_ghex_F,$STR_A3_A_CfgWeapons_V_HarnessOSpec_ghex_F0);
	VEST_HOLDER(V_BandollierB_tna_F,$STR_A3_A_CfgWeapons_V_BandollierB_tna_F0);
	VEST_HOLDER(V_PlateCarrierL_CTRG_grn_F,$STR_A3_A_CfgWeapons_V_PlateCarrierL_CTRG_grn_F0);
	VEST_HOLDER(V_PlateCarrierH_CTRG_grn_F,$STR_A3_A_CfgWeapons_V_PlateCarrierH_CTRG_grn_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_Black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_Black_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_light_Black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_light_Black_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_heavy_Black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_heavy_Black_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_Coyote_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_Coyote_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_light_Coyote_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_light_Coyote_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_heavy_Coyote_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_heavy_Coyote_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_Khaki_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_Khaki_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_light_Khaki_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_light_Khaki_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_heavy_Khaki_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_heavy_Khaki_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_MTP_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_MTP_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_light_MTP_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_light_MTP_F0);
	VEST_HOLDER(V_CarrierRigKBT_01_heavy_MTP_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_heavy_MTP_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_MTP_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_MTP_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_MTP_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_MTP_F0);
	VEST_HOLDER(V_Rangemaster_belt_taiga_F,$STR_A3_A_CfgWeapons_V_Rangemaster_belt_taiga_F0);
	VEST_HOLDER(V_BandollierB_taiga_F,$STR_A3_A_CfgWeapons_V_BandollierB_taiga_F0);
	VEST_HOLDER(V_TacVest_grn,$STR_A3_A_CfgWeapons_V_TacVest_grn0);
	VEST_HOLDER(V_CF_CarrierRig_F,$STR_A3_A_CfgWeapons_V_CF_CarrierRig_F0);
	VEST_HOLDER(V_CF_CarrierRig_Lite_F,$STR_A3_A_CfgWeapons_V_CF_CarrierRig_lite_F0);
	VEST_HOLDER(V_CF_CarrierRig_MG_F,$STR_A3_A_CfgWeapons_V_CF_CarrierRig_MG_F0);
	VEST_HOLDER(Aegis_V_ChestrigEast_RUtaiga_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_rutaiga0);
	VEST_HOLDER(Aegis_V_ChestrigEast_RUarid_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_ruarid0);
	VEST_HOLDER(Aegis_V_ChestrigEast_khk_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_khk0);
	VEST_HOLDER(Aegis_V_ChestrigEast_grn_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_grn0);
	VEST_HOLDER(Aegis_V_ChestrigEast_oli_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_oli0);
	VEST_HOLDER(Aegis_V_ChestrigEast_tan_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_tan0);
	VEST_HOLDER(Aegis_V_ChestrigEast_hex_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_hex0);
	VEST_HOLDER(Aegis_V_ChestrigEast_ghex_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_ghex0);
	VEST_HOLDER(Aegis_V_ChestrigEast_dst_F,$STR_A3_A_CfgWeapons_V_ChestRigEast_dst0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_arid_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_arid_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_grn_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_grn_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_khk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_khk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_blk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_blk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_Lite_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_Lite_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_Lite_arid_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_Lite_arid_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_Lite_grn_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_Lite_grn_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_Lite_khk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_Lite_khk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_Lite_blk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_Lite_blk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_GL_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_GL_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_GL_arid_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_GL_arid_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_GL_grn_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_GL_grn_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_GL_khk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_GL_khk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_GL_blk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_GL_blk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_CQB_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_CQB_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_CQB_arid_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_CQB_arid_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_CQB_grn_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_CQB_grn_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_CQB_khk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_CQB_khk_F0);
	VEST_HOLDER(Aegis_V_OCarrierLuchnik_CQB_blk_F,$STR_A3_A_CfgWeapons_Aegis_V_OCarrierLuchnik_CQB_blk_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_EAF_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_EAF_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_olive_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_olive_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_black_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_khk_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_khk_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_cqb_cbr_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_cqb_cbr_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_EAF_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_EAF_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_olive_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_olive_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_black_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_khk_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_khk_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_cbr_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_cbr_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_ctrg_ard_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_ctrg_ard_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_recon_ctrg_trp_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_recon_ctrg_trp_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_tac_olive_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_tac_olive_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_tac_black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_tac_black_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_tac_khk_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_tac_khk_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_tac_cbr_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_tac_cbr_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_holster_olive_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_holster_olive_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_holster_black_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_holster_black_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_holster_khk_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_holster_khk_F0);
	VEST_HOLDER(Aegis_V_CarrierRigKBT_01_holster_cbr_F,$STR_A3_A_CfgWeapons_V_CarrierRigKBT_01_holster_cbr_F0);
	VEST_HOLDER(Aegis_V_Ammo_Bandolier_F,$STR_A3_A_CfgWeapons_V_Ammo_Bandolier_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_rgr,$STR_A3_V_PlateCarrier2_alt_rgr_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_cbr,$STR_A3_V_PlateCarrier2_alt_cbr_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_khk,$STR_A3_V_PlateCarrier2_alt_khk_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_mtp,$STR_A3_V_PlateCarrier2_alt_mtp_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_oli,$STR_A3_V_PlateCarrier2_alt_oli_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_wdl,$STR_A3_V_PlateCarrier2_alt_wdl_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_tna,$STR_A3_V_PlateCarrier2_alt_tna_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_blk,$STR_A3_V_PlateCarrier2_alt_blk_F0);
	VEST_HOLDER(Aegis_V_PlateCarrier2_alt_desert,$STR_A3_V_PlateCarrier2_alt_desert_F0);

    /* Deprecated */
    DEPRECATED_CLASS(Vest_V_I_G_resistanceLeader_F,Vest_Base_F);;
    DEPRECATED_CLASS(Vest_V_CarrierRigKBT_01_Green_F,Vest_V_CarrierRigKBT_01_Olive_F);;
    DEPRECATED_CLASS(Vest_V_CarrierRigKBT_01_light_Green_F,Vest_V_CarrierRigKBT_01_light_Olive_F);;
    DEPRECATED_CLASS(Vest_V_CarrierRigKBT_01_heavy_Green_F,Vest_V_CarrierRigKBT_01_heavy_Olive_F);;
};