DEPRECATED_CLASS(V_I_G_resistanceLeader_F,V_TacVest_camo);
DEPRECATED_CLASS(V_CarrierRigKBT_01_Green_F,V_CarrierRigKBT_01_Olive_F);
DEPRECATED_CLASS(V_CarrierRigKBT_01_light_Green_F,V_CarrierRigKBT_01_light_Olive_F);
DEPRECATED_CLASS(V_CarrierRigKBT_01_heavy_Green_F,V_CarrierRigKBT_01_heavy_Olive_F);