class CfgMovesAnimal_Base_F
{
	//access = 1;
	collisionVertexPattern[] = {};
	collisionGeomCompPattern[] = {1};
	class Default
	{
	    //access = 3;
		file = "";
		looped = true;
		speed = 0.5;
		disableWeapons = true;
		enableOptics = true;
		disableWeaponsLong = false;
		canreload = true;
		showWeaponAim = true;
		enableMissile = false;
		enableBinocular = false;
		showItemInHand = false;
		showItemInRightHand = false;
		showHandGun = false;
		onLandBeg = false;
		onLandEnd = false;
		onLadder = false;
		canPullTrigger = true;
		duty = -0.51;
		predictSpeedCoef = 1;
		visibleSize = 1;
		aimPrecision = 1;
		relSpeedMin = 1;
		relSpeedMax = 1;
		soundEnabled = true;
		soundOverride = "";
		soundEdge[] = {0.5,1};
		soundEdge1 = 0.5;
		soundEdge2 = 1;
		terminal = false;
		limitGunMovement = true;
		variantsPlayer[] = {};
		variantsAI[] = {};
		equivalentTo = "";
		connectAs = "";
		variantAfter[] = {5,10,20};
		connectFrom[] = {};
		connectTo[] = {};
		interpolateWith[] = {};
		interpolateTo[] = {};
		interpolateFrom[] = {};
		aiming = aimingNo;
		leaning = aimingNo;
		untiltWeapon = aimingNo;
		aimingBody = aimingUpDefault;
		legs = legsNo;
		head = headDefault;
		leaningFactorBeg = 0;
		leaningFactorEnd = 0;
		leaningFactorZeroPoint = -1;
		leaningCorrectionAngleBeg = 0;
		leaningCorrectionAngleEnd = 0;
		interpolationSpeed = 6;
		interpolationRestart = 0;
		hasCollShapeSafe = false;
		collisionShapeSafe = "";
		boundingSphere = true;
		enableDirectControl = true;
		enableAutoActions = false;
		leftHandIKBeg = 0;
		leftHandIKEnd = 0;
		leftHandIKCurve = 0;
		rightHandIKCurve = 0;
		rightHandIKBeg = 0;
		rightHandIKEnd = 0;
		weaponIK = 0;
		preload = false;
		walkcycles = true;
		forceAim = false;
		showDisposableGun = false;
		headBobStrength = 0.5;
		headBobMode = 1;
	};
	class StandBase: Default
	{
		duty = -1;
		head = headDefault;
		speed = 1e+010;
		relSpeedMin = 0.7;
		relSpeedMax = 1.1;
		looped = true;
		soundEnabled = true;
		enableDirectControl = false;
		disableWeapons = true;
		disableWeaponsLong = true;
	};
	class DefaultDie: Default
	{
		aiming = aimingNo;
		legs = legsNo;
		head = headNo;
	};
	class ManActions
	{
		Stop = "";
		StopRelaxed = "";
		TurnL = "";
		TurnR = "";
		TurnLRelaxed = "";
		TurnRRelaxed = "";
		Default = "";
		JumpOff = "";
		ReloadMagazine = "";
		ReloadMGun = "";
		ReloadAT = "";
		ReloadMortar = "";
		ThrowGrenade = "";
		WalkF = "";
		WalkLF = "";
		WalkRF = "";
		WalkL = "";
		WalkR = "";
		WalkLB = "";
		WalkRB = "";
		WalkB = "";
		SlowF = "";
		SlowLF = "";
		SlowRF = "";
		SlowL = "";
		SlowR = "";
		SlowLB = "";
		SlowRB = "";
		SlowB = "";
		FastF = "";
		FastLF = "";
		FastRF = "";
		FastL = "";
		FastR = "";
		FastLB = "";
		FastRB = "";
		FastB = "";
		EvasiveForward = "";
		EvasiveLeft = "";
		EvasiveRight = "";
		EvasiveBack = "";
		StartSwim = "";
		StopSwim = "";
		Down = "";
		Up = "";
		PlayerStand = "";
		PlayerCrouch = "";
		PlayerProne = "";
		Lying = "";
		Stand = "";
		Combat = "";
		Crouch = "";
		CanNotMove = "";
		Civil = "";
		CivilLying = "";
		FireNotPossible = "";
		Die = "";
		WeaponOn = "";
		WeaponOff = "";
		StrokeFist = "";
		StrokeGun = "";
		SitDown = "";
		Salute = "";
		BinocOn = "";
		BinocOff = "";
		PutDown = "";
		PutDownEnd = "";
		Medic = "";
		Treated = "";
		LadderOnDown = "";
		LadderOnUp = "";
		LadderOff = "";
		LadderOffTop = "";
		LadderOffBottom = "";
		GetInLow = "";
		GetInMedium = "";
		GetInHigh = "";
		GetOutLow = "";
		GetOutMedium = "";
		GetOutHigh = "";
		TakeFlag = "";
		HandGunOn = "";
		LookAround = "";
		Eat = "";
		StopEat = "";
		Rest = "";
		StopRest = "";
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed = 8;
			limitFast = 5.5;
			useFastMove = false;
			stance = ManStanceUndefined;
			upDegree = 0;
		};
	};
	class Interpolations{};
	transitionsInterpolated[] = {};
	transitionsSimple[] = {};
	transitionsDisabled[] = {};
	class BlendAnims
	{
		aimingDefault[] = {head,1};
		untiltWeaponDefault[] = {};
		legsDefault[] = {};
		headDefault[] = {Head,1};
		aimingNo[] = {};
		legsNo[] = {};
		headNo[] = {};
		aimingUpDefault[] = {};
	};
};