DEPRECATED_CLASS(O_W_Static_AA_F,Atlas_O_W_Static_AA_F);
DEPRECATED_CLASS(B_L_Static_AA_F,Atlas_B_L_Static_AA_F);
DEPRECATED_CLASS(B_E_Static_AA_F,Atlas_B_G_Static_AA_F);
DEPRECATED_CLASS(I_I_AA_01_weapon_F,Atlas_I_I_AA_01_weapon_F);
DEPRECATED_CLASS(I_I_Static_AA_F,Atlas_I_I_Static_AA_F);