#include "\A3_Aegis\basicDefines_A3.hpp"
#include "cfgPatches.hpp"
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class SensorTemplatePassiveRadar;
class SensorTemplateAntiRadiation;
class SensorTemplateActiveRadar;
class SensorTemplateIR;
class SensorTemplateVisual;
class SensorTemplateMan;
class SensorTemplateLaser;
class SensorTemplateNV;
class SensorTemplateDataLink;
class SlotInfo;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class UnderBarrelSlot;
class MuzzleSlot_556;
class MuzzleSlot_65;
class MuzzleSlot_762;
class MuzzleSlot_MG;
class CowsSlot_Rail;
class PointerSlot_Rail;
class UnderBarrelSlot_rail;
//#include "cfgAmmo.hpp"
//#include "cfgMagazines.hpp"
#include "cfgWeapons.hpp"