DEPRECATED_CLASS(I_I_APC_Tracked_01_AA_F,Atlas_I_I_APC_Tracked_01_AA_F);
DEPRECATED_CLASS(I_I_APC_Tracked_01_CRV_F,Atlas_I_I_APC_Tracked_01_CRV_F);
DEPRECATED_CLASS(I_I_APC_Tracked_01_rcws_F,Atlas_I_I_APC_Tracked_01_rcws_F);