DEPRECATED_CLASS(I_I_Ejection_Seat_Plane_Fighter_05_F,Atlas_I_I_Ejection_Seat_Plane_Fighter_05_F);
DEPRECATED_CLASS(I_I_Plane_Fighter_05_F,Atlas_I_I_Plane_Fighter_05_F);
DEPRECATED_CLASS(I_I_Plane_Fighter_05_Stealth_F,Atlas_I_I_Plane_Fighter_05_Stealth_F);